#: default system-wide niseroku.toml

#: bind-addr is the network address to bind all listener services to, the
#: default is empty which listens on all host addresses
#
#bind-addr = ""

#: buildpack-path is the path to a checkout of the enjenv heroku buildpack.
#: When set, this checkout is copied as-is each time, leaving the task of
#: staying up-to-date to the niseroku admins rather than cloning the default
#: repository each time a build is performed. The default respository is of
#: course: https://github.com/go-enjin/enjenv-heroku-buildpack.git
#
#buildpack-path = "/path/to/custom-enjenv-heroku-buildpack"

#: log-file captures both STDOUT and STDERR from the main niseroku processes.
#: Setting this to an empty string will disable capturing STDOUT and STDERR,
#: leaving the output streams to be collected by the operating system's init
#: service
#
log-file = "/var/log/niseroku.log"

#: enable-ssl configures whether or not niseroku will listen for HTTPS requests
#: on the (ports.https) port
#
#enable-ssl = false

#: account-email is the email address uses when registering with Let's Encrypt
#: and accepting the terms-of-service
#
#account-email = ""

#: include-slugs configures whether or not to start all slugs on startup and/or
#: stop all slugs on shutdown
#
[include-slugs]
on-start = true
#on-stop = false

#: timeouts are used to configure how long niseroku awaits for things to
#: happen
#
[timeouts]
slug-startup = "60s"
ready-interval = "1s"
origin-request = "60s"

#: run-as configures the user and group niseroku switches to when started as
#: root (UID=0), after opening any necessary privileged ports (ie: 80, 443)
#
[run-as]
user = "www-data"
group = "www-data"

#: ports configure the various niseroku listener services
#: ports.git is for the git repository service endpoint, clients need to know
#: this value so that developers can push commits for deployment
#: ports.app-start and ports.app-end configure the range of available ports
#: used for running application slugs, a new random port is selected each time
#: a slug build process succeeds and upon the newly built slug actually
#: starting up and opening the specified port, the application's configuration
#: is updated with this newly selected port (this is how failed builds are
#: prevented from disrupting existing builds already running)
#
[ports]
git = 2403
http = 80
https = 443
app-start = 4200
app-end = 4400

#: paths configure where niseroku stores configurations and runtime files
#: paths.etc is where configuration files are stored
#: paths.tmp is where temporary files are stored, note that this path should
#: not be the operating system's actual $TMP directory
#: paths.var is where the runtime files are stored, such as application logs,
#: git repositories and built slugs
#
[paths]
etc = "/etc/niseroku"
tmp = "/var/lib/niseroku/tmp"
var = "/var/lib/niseroku"
