#: BEGIN NISEROKU CONFIG - enjenv niseroku config --help

#: bind-addr         (string)
#:     * ip address for niseroku services to bind listeners
#:     * requires niseroku-{proxy,repos} restart if changed
#
bind-addr = "0.0.0.0"

#: enable-ssl        (bool)
#:     * reverse-proxy will bind an HTTPS autocert listener
#:     * requires account-email to be set
#:     * requires niseroku-proxy restart if changed
#
enable-ssl = false

#: account-email     (email@address.string)
#:     * email address used for the Let's Encrypt account
#:     * implies agreement with Let's Encrypt terms of service
#:     * requires niseroku-proxy restart if changed
#
account-email = ""

#: buildpack-path    (path)
#:     * specifies an enjenv-heroku-buildpack checkout to use
#:     * requires niseroku-repos reload or restart if changed
#
buildpack-path = "https://github.com/go-enjin/enjenv-heroku-buildpack.git"

#: log-file          (path)
#:     * specifies the path to use for logging services
#:     * both reverse-proxy and git-repository log to this file
#:     * requires niseroku-{proxy,repos} reload or restart if changed
#
log-file = ""

#: slug-nice         (number: -20 to 20)
#:     * renice all slugs run to the given priority
#:     * be careful with this setting!
#:     * requires niseroku app restart if changed
#
slug-nice = 0

#: [include-slugs]   (section)
#:     * configures when to include slugs in the niseroku lifecycle
#:     * requires niseroku-proxy reload or restart if changed
#
[include-slugs]
  on-start = true #: start all stopped slugs on reverse-proxy startup
  on-stop = false #: stop all running slugs on reverse-proxy shutdown

#: [timeouts]        (section)
#:     * global reverse-proxy timeout settings
#:     * uses the Go time.Duration format, see: https://pkg.go.dev/time#ParseDuration
#:     * requires niseroku-proxy reload or restart if changed
#
[timeouts]
  #: slug-startup      (time.Duration)
  #:     * maximum time to allow slugs to open the expected port
  #
  slug-startup = "5m0s"

  #: ready-interval    (time.Duration)
  #:     * frequency at which niseroku checks expected ports to open
  #
  ready-interval = "1s"

  #: origin-request    (time.Duration)
  #:     * maximum time to allow slugs to perform a given request
  #
  origin-request = "1m0s"

#: [proxy-limit]     (section)
#:     * reverse-proxy request rate-limiting settings
#:     * requires niseroku-proxy reload or restart if changed
#
[proxy-limit]
  #: ttl (time.Duration) - rate-limiter cached values lifetime
  #
  ttl = "8760h0m0s"

  #: max (int) - concurrent requests allowed before rate limiting
  #
  max = 150.0

  #: burst (int) - concurrent requests allowed within a brief timeframe before rate limiting
  #
  burst = 150

  #: max-delay (time.Duration) - maximum time to delay requests before 429 response
  #
  max-delay = "2s"

  #: delay-scale (int) - number of limit-check intervals within the max-delay timeframe
  #
  delay-scale = 10

  #: log-allowed (bool) - log when already delayed requests are allowed to pass
  #
  log-allowed = false

  #: log-delayed (bool) - log each time a request is delayed by rate-limiting
  #
  log-delayed = false

  #: log-limited (bool) - log each time a request is limited (429 response)
  #
  log-limited = true

#: [run-as]          (section)
#:     * when run as root, drop privileges to the specified user and group
#:     * requires niseroku-{proxy,repos} restart if changed
#:     * may also require "sudo enjenv niseroku fix-fs" to correct file ownership errors
#
[run-as]
  user = "www-data"
  group = "www-data"

#: [ports]           (section)
#:     * all ports specified are used with the bind-addr setting
#
[ports]
  #: git               (number: 1 to 65534)
  #:     * requires niseroku-repos restart if changed
  #
  git = 2403

  #: http               (number: 1 to 65534)
  #:     * requires niseroku-proxy restart if changed
  #
  http = 80

  #: https              (number: 1 to 65534)
  #:     * setting to anything other than 443 has not been tested
  #:     * requires niseroku-proxy restart if changed
  #
  https = 443

  #: app-start          (number: 1 to 65534)
  #:     * start of application port range
  #
  app-start = 4200

  #: app-end            (number: 1 to 65534)
  #:     * end of application port range
  #
  app-end = 4400

#: [paths]            (section)
#:     * top-levels of where niseroku files live
#:     * requires niseroku-{proxy,repos} restart if changed
#:     * may also require "sudo enjenv niseroku fix-fs" to correct file ownership errors
#
[paths]
  #: etc                (path)
  #:     * where configuration files live
  #
  etc = "/etc/niseroku"

  #: var                (path)
  #:     * where persistent files live
  #
  var = "/var/lib/niseroku"

  #: tmp                (path)
  #:     * where temporary files live
  #
  tmp = "/var/lib/niseroku/tmp"

#: END NISEROKU CONFIG - enjenv niseroku config --help
