#: default system-wide niseroku.toml

#buildpack-path = "/path/to/custom-enjenv-heroku-buildpack"

log-file = "/var/log/niseroku.log"
#enable-ssl = false
#account-email = ""

[timeouts]
slug-startup = "60s"

[run-as]
user = "www-data"
group = "www-data"

[ports]
git = 2222
http = 80
https = 443

[paths]
etc = "/etc/niseroku"
tmp = "/var/lib/niseroku/tmp"
var = "/var/lib/niseroku"